# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "866690ab772354418b761488be19955d"
name = "my-new-awesome-app"
handle = "my-new-awesome-app-161"
application_url = "https://dollars-vulnerable-diagnosis-monitor.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-cf9e7b7a.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dollars-vulnerable-diagnosis-monitor.trycloudflare.com/auth/callback",
  "https://dollars-vulnerable-diagnosis-monitor.trycloudflare.com/auth/shopify/callback",
  "https://dollars-vulnerable-diagnosis-monitor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
